# -*- coding: utf-8 -*-
"""
Created on Tue Mar  2 16:55:10 2021

@author: Abhinav.Bajpai
"""

import gc
##Clear variable/objects from workspace to free up memory
for name in dir():
    if not name.startswith('_'):
        del globals()[name]
dir()



import numpy as np 
import pandas as pd
import matplotlib as mp
import seaborn as sns
import os
import matplotlib.pyplot as plt
import math
import scipy.stats as stats
import datetime 
from scipy.stats import chi2_contingency ## for chi sq test 
from scipy.stats import   ttest_1samp,ttest_ind ##For t test
from scipy.stats import variation  
from statsmodels.formula.api import ols      # For n-way ANOVA
from statsmodels.stats.anova import _get_covariance,anova_lm # For n-way ANOVA
from sklearn.preprocessing import StandardScaler ##For zscore scaling 
from scipy.cluster.hierarchy import dendrogram, linkage
 ##for clustering
from sklearn.cluster import KMeans  ## for k means
sns.set(color_codes=True) 

def remove_outlier(col):
    sorted(col)
    Q1,Q3=np.percentile(col,[25,75])
    IQR=Q3-Q1
    print("Interquartile range of the column is ",IQR)
    lower_range= Q1-(1.5 * IQR)
    upper_range= Q3+(1.5 * IQR)
    return lower_range, upper_range


def treat_outlier_5_95(x):
    # taking 5,25,75 percentile of column
    q5= np.percentile(x,5)
    q25=np.percentile(x,25)
    q75=np.percentile(x,75)
    dt=np.percentile(x,95)
    #calculationg IQR range
    IQR=q75-q25
    print("Interquartile range of the column is ",IQR)
    #Calculating minimum threshold
    lower_bound=q25-(1.5*IQR)
    upper_bound=q75+(1.5*IQR)
    #Capping outliers
    return x.apply(lambda y: dt if y > upper_bound else y).apply(lambda y: q5 if y < lower_bound else y)



# Use 3 decimal places in output display
pd.set_option("display.precision", 3)

# Don't wrap repr(DataFrame) across additional lines
##pd.set_option("display.expand_frame_repr", False)

# Set max rows displayed in output
pd.set_option("display.max_rows", 100)

##Set max columns displayed in output 
pd.set_option("display.max_columns", 20)

pd.set_option("display.max_colwidth",20)

vehicles_orig=pd.read_csv('E:\\AbhinavB\\Kaggle\\Python related\\DSBA related\\Week10-Clustering\\vehicle.csv')

vehicles=vehicles_orig.copy()

##Checking duplicate values
dups=vehicles.duplicated()
print("The no of duplciates ",dups.sum())

##Checking missing values
vehicles.isnull().sum()
vehicles=vehicles.dropna()

vehicles['class'].value_counts()

##Outliers 
vehicles2=vehicles.drop('class',axis=1)

vehicles2.boxplot()
plt.xticks(rotation = 90);

##Scaling
sobj=StandardScaler()
data_scaled=sobj.fit_transform(vehicles2)
data_scaled=pd.DataFrame(data_scaled,columns=vehicles2.columns)

data_scaled.boxplot()
plt.xticks(rotation = 90);

from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_samples, silhouette_score
##Hierarchical cluster 
HClust = linkage(data_scaled, method = 'ward')
dend = dendrogram(HClust)
dend = dendrogram(HClust,
                 truncate_mode='lastp',
                 p = 25,# we are looking at the last 25 merges
                 )

#Method 1
clusters_1 = fcluster(HClust, 2, criterion='maxclust')
clusters_1
# Method 2
clusters_2 = fcluster(HClust, 60, criterion='distance')
clusters_2

#Now, let us go ahead and check whether the number of clusters generated by the 'maxclust' criterion is same as the number of clusters generated by the 'distance' criterion.
np.array_equal(clusters_1,clusters_2)

vehicles2['Cluster_Hierar']=clusters_1

k_means2 = KMeans(n_clusters = 2,random_state=1)
k_means2.fit(data_scaled)
k_means2.labels_

wss =[] 
for i in range(1,15):
    KM = KMeans(n_clusters=i,random_state=0)
    KM.fit(data_scaled)
    wss.append(KM.inertia_)

plt.plot(range(1,15), wss)
plt.grid()
plt.show()

################quiz data 

leaf_orig=pd.read_csv('E:\\AbhinavB\\Kaggle\\Python related\\DSBA related\\Week10-Clustering\\leaf_data_uci_updated.csv')

leaf=leaf_orig.copy()

##Checking duplicate values
dups=leaf.duplicated()
print("The no of duplciates ",dups.sum())

##Checking missing values
leaf.isnull().sum()
#vehicles=vehicles.dropna()

##Outliers 

leaf.boxplot()
plt.xticks(rotation = 90);

##Scaling
sobj=StandardScaler()
data_scaled=sobj.fit_transform(leaf)
data_scaled=pd.DataFrame(data_scaled,columns=leaf.columns)
data_scaled.boxplot()
plt.xticks(rotation = 90);


##Hierarchical cluster 
HClust = linkage(data_scaled, method = 'ward')
dend = dendrogram(HClust)
dend = dendrogram(HClust,
                 truncate_mode='lastp',
                 p = 25,# we are looking at the last 25 merges
                 )

#Method 1
clusters_1 = fcluster(HClust, 2, criterion='maxclust')
clusters_1
# Method 2
clusters_2 = fcluster(HClust, 60, criterion='distance')
clusters_2

#Now, let us go ahead and check whether the number of clusters generated by the 'maxclust' criterion is same as the number of clusters generated by the 'distance' criterion.
np.array_equal(clusters_1,clusters_2)

leaf['Cluster_Hierar']=clusters_1

##K means

k_means2 = KMeans(n_clusters = 2,random_state=1)
k_means2.fit(data_scaled)
k_means2.labels_

wss =[] 
for i in range(1,15):
    KM = KMeans(n_clusters=i,random_state=1)
    KM.fit(data_scaled)
    wss.append(KM.inertia_)

plt.plot(range(1,15), wss)
plt.grid()
plt.show()

k_means4 = KMeans(n_clusters = 4,random_state=0)
k_means4.fit(data_scaled)
k_means4.inertia_
labels4=k_means4.labels_
labels4


np.random.seed(7)
array1=np.array(np.random.rand(20)).reshape(10,2)
sobj=StandardScaler()
data_scaled=sobj.fit_transform(array1)
##data_scaled=pd.DataFrame(data_scaled,columns=leaf.columns)
k_mean2_arr=KMeans(n_clusters=2,random_state=0)
k_mean2_arr.fit(array1)
k_mean2_arr.inertia_
lbls=k_mean2_arr.labels_

from sklearn.metrics import silhouette_samples, silhouette_score


silhouette_score(data_scaled,lbls)

